# Generated by Django 4.1.7 on 2023-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_eventt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventt",
            name="creator",
        ),
        migrations.AddField(
            model_name="eventt",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
