# Generated by Django 4.1.7 on 2023-04-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_remove_eventt_creator_eventt_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
