# Generated by Django 4.1.7 on 2023-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_venue_address_alter_venue_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventt",
            name="cost_per_person",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
