# Generated by Django 4.1.7 on 2023-04-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_alter_eventt_cost_per_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("number", models.CharField(max_length=10)),
                ("num_tickets", models.PositiveIntegerField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("razorpay_payment_id", models.CharField(max_length=100)),
                ("razorpay_order_id", models.CharField(max_length=100)),
                ("razorpay_signature", models.CharField(max_length=100)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
